### ISSUE TITLE
Allow space for delegate about item

### ISSUE THREAD

**Issue by picatextra** [X-CASH-official/xcash-core#10]
When using the command delegate_update, it check the number of parameters =2 ,
but `delegate_update about` should allow parameters >= 2

```
[wallet XCA1mN]: delegate_update about VOTE FOR ME !
Error: Failed to send the vote
Invalid parameters
[wallet XCA1mN]: delegate_update about "VOTE FOR ME !"
Error: Failed to send the vote
Invalid parameters
```

**Comment by zachhildreth** [comment]
Hi @picatextra 

This behavior has been changed in commit 9f2240c7e026dcb5b07b5fe1d5323b8c6906c8ea

This falls into a improvement, but is also a bug since most users will want to use more than one word when updating the below categories, so we are awarding the bug bounty for this bug to you!

### CVSS Score
### We have determined that the [CVSS score for this bug](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N/CR:L/IR:L/AR:L/MAV:L/MAC:L/MPR:N/MUI:N/MS:U/MC:N/MI:N/MA:N&version=3.1) is a 0

So according to the [Bug Bounty official documentation](https://docs.xcash.foundation/contribute/bug-bounty-program) this bug qualifies for a award between $5.00 and 25.00 USD

We have calculated the final amount in USD based on the following criteria


| Question                                     | Answer  |
| -------------------------------------------- | --------------------------- |
| How long I have spent on the bug                                      | N/A |
| How often does the bug occur                                            | When a user updates there "about, team, server_settings" data |
| Was there any modification to the code to create the bug  | NO |
| Did the user provide a full code fix                                | NO |
| Did the bug have to do with multi-threading                       | NO |
| Could the tester use a debugger, static analysis or both |both|
| Are we currently in Alpha, Beta or Live implementation of DPOPS |ALPHA|
 

## Based on the above the team has decided that the final awarded amount will be $10.00 USD

### Please post a X-CASH Wallet address in the comments, and we will send the payment in a public transaction, post the transaction hash and then close the issue.

Thank you for helping out the DPOPS by finding this bug.

**Comment by picatextra** [comment]
XCA1ka4bXH1bnvdT8vti1S12PfyH8fJ5XDUXyNRusyMRTBfFCawywJyCV5vvG38h71GAv77WotbmwbmbJen5bQpC7GeVx8gSws

**Comment by plbgnt** [comment]
**Bounty Paid ✅** 
--------------
Date: **21/11/2019**
Amount (USD): **$10**
Amount (XCASH): **283148.53 XCASH**
Spot Price: **0.0000353171538862627 USD/XCASH**
XCASH Address: **XCA1ka4bXH1bnvdT8vti1S12PfyH8fJ5XDUXyNRusyMRTBfFCawywJyCV5vvG38h71GAv77WotbmwbmbJen5bQpC7GeVx8gSws** 
Tx Hash: **8893adb1378ce71c7a9f0801cb9694a4cd0915224a127f27e590450c7e86aef1** 
Link: **https://explorer.x-cash.org/Transaction?data=8893adb1378ce71c7a9f0801cb9694a4cd0915224a127f27e590450c7e86aef1**
